name: Update README.md

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 12:00 PM VNT (5:00 AM UTC)
    - cron: '0 9 * * *' # Runs at 4:00 PM VNT (9:00 AM UTC)
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run GitHub Stats Action
      uses: minhpv-2595/github-stats@master
      env:
        BRANCH_NAME: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        COMMIT_MESSAGE: "🚀 update metrics"
        COMMIT_USER_NAME: "minhpv-2595"
        COMMIT_USER_EMAIL: "pham.van.minh@sun-asterisk.com"
        WAKATIME_DATA: "EDITORS,LANGUAGES,PROJECTS,OPERATING_SYSTEMS"
        SHOW_METRICS: "COMMIT_TIME_OF_DAY,LANGUAGE_PER_REPO,COMMIT_DAYS_OF_WEEK"
        TIME_ZONE: "Asia/Ho_Chi_Minh"
        TIME_LAYOUT: "2006-01-02 15:04:05 MST"
        SHOW_LAST_UPDATE: "true"
        ONLY_MAIN_BRANCH: "true"
        HIDE_REPO_INFO: "true"
        WAKATIME_RANGE: "all_time"
